name: CI/CD

on:
  schedule:
    - cron: '0 0 * * *' # Exécuter chaque jour à minuit
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Fetch and send email
        run: npm run send

      - name: Generate artifact
        uses: actions/upload-artifact@v2
        with:
          name: New Jobs
          path: public
