name: CI/CD Generate artifact and send email

on:
  schedule:
    - cron: '0 0 * * *' # Exécuter chaque jour à minuit
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate artifact
        uses: actions/upload-artifact@v2
        with:
          name: jobs
          path: public

      # - name: Send email
      #   run: ts-node src/services/send-email.ts
